.\" This document is in the public domain.
.\" vim: fdm=marker
.
.\" FRONT MATTER {{{
.Dd Jul 16, 2012
.Os
.Dt BS-UPDATE 1
.
.Sh NAME
.Nm bs-update
.Nd Update packages in a Build Service from upstream sources.
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h
.Nm
.Op Fl A Ar BSAPI
.Op Fl P Ar PROJECT
.Op Fl n
.Op Fl p Ar PACKAGE
.Op Fl t Ar URL
.Ar TAG
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
makes it easier to keep packages in a Build Service
up-to-date with respect to their upstream sources.
.
.Bl -tag -width "xx"
.It Fl h
Display a usage description.
.
.It Fl A Ar BSAPI
Use Build Service at
.Ar BSAPI
(URL or alias).
.
.It Fl P Ar PROJECT
Update Build Service package of
.Ar PROJECT .
.
.It Fl n
Report values derived from
configuration files
(if any) and command line arguments.
.
.It Fl p Ar PACKAGE
Update Build Service
.Ar PACKAGE .
.
.It Fl t Ar URL
Download the source tarball from
.Ar URL .
.
.It Ar TAG
Update the package from
.Ar TAG .
.El
.Pp
Option arguments are subjected to shell expansion.
.
.Pp
.
Given a Build Service API URL, project and package names, a tarball
URL, and a version number,
.Nm
will
.
.Pp
.
.Bl -enum -compact
.It
fetch the tarball from the URL,
.It
check out the package from the Build Service,
.It
update the tarball source with the downloaded tarball,
.It
update the spec file source with a template from that tarball,
.It
commit the changes.
.El
.
.\" DESCRIPTION }}}
.\" .Sh IMPLEMENTATION NOTES
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Nm
itself does not use any environment variables.
It is, however, implemented in terms of third-party commands
which
.Em do
use them.
This means
.Nm
may be influenced by environment variables used by
.Xr sh 1 ,
.Xr osc 1 ,
.Xr tar 1 ,
.Xr curl 1 or Xr wget 1 ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.Sh FILES
.Nm
recognizes two optional configuration files,
.Pa .bs-update-hooks
and
.Pa .bs-update .
They are sourced from the current directory before command line
arguments are processed, in the order they are named above.
These two files are expected to provide
.Nm
with any of the following:
.Ss Shell functions
.Pp
. Bl -ohang
. It Fn bs_tarball_hook
If this function exists it is executed at the root of the extracted
tarball before it is packed again.
. El
.Ss Variables
.Pp
. Bl -tag -compact
. It Va bs_apiurl
Used unless
.Fl A
is given.
. It Va bs_project
Used unless
.Fl P
is given.
. It Va bs_dloadurl
Used unless
.Fl t
is given.
. El
.\" FILES }}}
.\" EXAMPLES {{{
.Sh EXAMPLES
.Bd -literal
git clone git@github.com:roman-neuhauser/rnt.git
cd rnt
printf "%s='%s'\\n" \\
  bs_package rnt \\
  bs_dloadurl 'https://github.com/roman-neuhauser/$bs_package/tarball/$tag' \\
  > .bs-update
vim GNUmakefile
git commit -a
git tag -a v42.69
git push origin master v42.69
bs-update -P home:roman-neuhauser v42.69
.Ed
.\" EXAMPLES }}}
.\" DIAGNOSTICS {{{
.Sh DIAGNOSTICS
.Nm
exits with
.Li 0
on success, and with
.Li >0
otherwise.
.\" DIAGNOSTICS }}}
.\" .Sh COMPATIBILITY
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr git 1 ,
the openSUSE Build Service
.Aq https://build.opensuse.org/ ,
and its wiki
.Aq http://en.opensuse.org/Portal:Build_Service .
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.
.Nm
and this manual page are written by
.Aq neuhauser@sigpipe.cz .
.Pp
See
.Aq https://github.com/roman-neuhauser/bs-update/ .
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Aq https://github.com/roman-neuhauser/bs-update/issues .
.\" BUGS }}}
