.\" This document is in the public domain.
.\" vim: fdm=marker
.
.\" FRONT MATTER {{{
.Dd Jul 16, 2012
.Os
.Dt BS-UPDATE 1
.
.Sh NAME
.Nm bs-update
.Nd Update packages in a Build Service from upstream sources.
.\" FRONT MATTER }}}
.
.\" SYNOPSIS {{{
.Sh SYNOPSIS
.Nm
.Fl h
.Nm
.Op Fl A Ar BSAPI
.Op Fl C
.Op Fl P Ar PROJECT
.Op Fl b
.Op Fl d Ar URL
.Op Fl m Ar COMMITMSG
.Op Fl n
.Op Fl p Ar PACKAGE
.Op Fl s Ar SPECFILE
.Op Fl t Ar TARBALL
.Ar TAG
.\" SYNOPSIS }}}
.
.\" DESCRIPTION {{{
.Sh DESCRIPTION
.Nm
makes it easier to keep packages in a Build Service
up-to-date with respect to their upstream sources.
.
.Pp
.
Given a Build Service API URL, project and package names, a tarball
URL, and a version number,
.Nm
will
.
.Pp
.
.Bl -enum -compact
.It
fetch the tarball from the URL,
.It
check out the package from the Build Service,
.It
update the tarball source with the downloaded tarball,
.It
update the spec file source with a template from that tarball,
.It
commit the changes.
.El
.
.Bl -tag -width "xx"
.It Fl h
Display a usage description.
.
.It Fl A Ar BSAPI
Use Build Service at
.Ar BSAPI
(URL or alias).
Defaults to
.Va $bsu_bs_apiurl .
.
.It Fl C
Skip the
.Nm osc
.Cm commit
step.
Sets
.Va $bsu_bs_commit
to
.Li 0 .
.
.It Fl P Ar PROJECT
Update Build Service package of
.Ar PROJECT .
Defaults to
.Va $bsu_bs_project .
.
.It Fl b
Run
.Nm osc
.Ar build
before
.Nm osc
.Ar commit .
If the build fails,
.Nm
aborts.
Sets
.Va $bsu_test_build .
.
.It Fl d Ar URL
Retrieve the source tarball from
.Ar URL .
If
.Ar URL
is
.Dq \&. ,
.Nm
uses
.Xr git-archive 1
in
.Va $PWD .
Otherwise,
.Nm
uses
.Xr wget 1 .
Defaults to
.Va $bsu_dloadurl .
.
.It Fl m Ar COMMITMSG
Use
.Ar COMMITMSG
for the commit in Build Service.
Defaults to
.Dl Dq Update to version Va $bsu_version .
.
.It Fl n
Report values derived from
configuration files and command line arguments, then exit.
.
.It Fl p Ar PACKAGE
Update Build Service
.Ar PACKAGE .
Defaults to
.Va $bsu_bs_package .
.
.It Fl s Ar SPECFILE
Use
.Ar SPECFILE Ns Li .in
from
.Va $bsu_tarball ,
commit
.Ar SPECFILE
into the Build Service.
All occurrences of
.Li __VERSION__
in
.Ar SPECFILE
are replaced with the value of
.Va $bsu_version .
Defaults to
.Va $bsu_bs_package Ns Li .spec .
.
.It Fl t Ar TARBALL
Use
.Ar TARBALL
for the name of the downloaded file.
Defaults to
.Va $bsu_bs_package Ns Li - Ns Va $bsu_version Ns Li .tar.gz .
.
.It Ar TAG
Update the package from
.Ar TAG .
In the absence of
.Fn bsu_version_hook ,
.Va $bsu_version
is derived from
.Ar TAG
by stripping the initial
.Li "v"
if any.
.El
.Pp
Option arguments are subjected to shell expansion.
.
.\" DESCRIPTION }}}
.\" .Sh IMPLEMENTATION NOTES
.\" ENVIRONMENT {{{
.Sh ENVIRONMENT
.Nm
itself does not use any environment variables.
It is, however, implemented in terms of third-party commands
which
.Em do
use them.
This means
.Nm
may be influenced by environment variables used by
.Xr sh 1 ,
.Xr osc 1 ,
.Xr tar 1 ,
.Xr curl 1 or Xr wget 1 ,
possibly others.
.\" ENVIRONMENT }}}
.\" FILES {{{
.Sh FILES
.Nm
recognizes two optional configuration files,
.Pa .bs-update-hooks
and
.Pa .bs-update .
They are sourced from the current directory before command line
arguments are processed, in the order they are named above.
These two files are expected to provide
.Nm
with any of the following:
.Ss Shell functions
.Pp
. Bl -ohang
. It Fn bsu_tarball_hook
If this function exists it is executed at the root of the extracted
tarball before it is packed again.
.
. It Fn bsu_version_hook
If this function exists it is executed with
.Ar $1
set to the value of the
.Ar TAG
argument, and its output is used as the value of
.Va $bsu_version .
. El
.Ss Variables
.Pp
. Bl -tag -width "x"
. It Va bsu_bs_apiurl
Used unless
.Fl A
is given.
. It Va bsu_bs_commit
Used unless
.Fl C
is given.
. It Va bsu_bs_commitmsg
Used unless
.Fl m
is given.
. It Va bsu_bs_package
Used unless
.Fl p
is given.
. It Va bsu_bs_project
Used unless
.Fl P
is given.
. It Va bsu_dloadurl
Used unless
.Fl d
is given.
. It Va bsu_dryrun
Used unless
.Fl n
is given.
. It Va bsu_specfile
Used unless
.Fl s
is given.
. It Va bsu_tarball
Used unless
.Fl t
is given.
. It Va bsu_test_build
Used unless
.Fl b
is given.
. El
.\" FILES }}}
.\" EXAMPLES {{{
.Sh EXAMPLES
.Bd -literal
git clone git@github.com:roman-neuhauser/rnt.git
cd rnt
printf "%s='%s'\\n" \\
  bsu_bs_package rnt \\
  bsu_dloadurl 'https://github.com/roman-neuhauser/$bsu_bs_package/tarball/$bsu_tag' \\
  > .bs-update
vim GNUmakefile
git commit -a
git tag -a v42.69
git push origin master v42.69
bs-update -P home:roman-neuhauser v42.69
.Ed
.\" EXAMPLES }}}
.\" DIAGNOSTICS {{{
.Sh DIAGNOSTICS
.Nm
exits with
.Li 0
on success, and with
.Li >0
otherwise.
.\" DIAGNOSTICS }}}
.\" .Sh COMPATIBILITY
.\" SEE ALSO {{{
.Sh SEE ALSO
.Xr git 1 ,
the openSUSE Build Service
.Aq https://build.opensuse.org/ ,
and its wiki
.Aq http://en.opensuse.org/Portal:Build_Service .
.\" SEE ALSO }}}
.\" .Sh STANDARDS
.\" .Sh HISTORY
.\" AUTHORS {{{
.Sh AUTHORS
.
.Nm
and this manual page are written by
.Aq neuhauser@sigpipe.cz .
.Pp
See
.Aq https://github.com/roman-neuhauser/bs-update/ .
.\" AUTHORS }}}
.\" BUGS {{{
.Sh BUGS
No doubt plentiful.
Please report them at
.Aq https://github.com/roman-neuhauser/bs-update/issues .
.\" BUGS }}}
